#!/usr/bin/env bash
mkdir -p dist
echo "build src/proxise.ls -> dist/proxise.js ..."
./node_modules/.bin/lsc -cbp src/proxise.ls > dist/proxise.js
echo "minifying proxise.js ..."
./node_modules/.bin/uglifyjs dist/proxise.js > dist/proxise.min.js
echo "done."
